using FlightsReservation.BLL.Interfaces.Services;
using FlightsReservation.DAL.Entities.Model;
using QuestPDF.Fluent;
using QuestPDF.Helpers;

namespace FlightsReservation.BLL.Services.UtilityServices;

public class QuestPdfService : IPdfService
{
    public async Task<MemoryStream> GenerateTicketPdfAsync(Passenger passenger, Flight flight)
    {
        var stream = new MemoryStream();

        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(12));
                page.PageColor(Colors.White);

                page.Header()
                    .Text("Flight E-Ticket")
                    .SemiBold().FontSize(22).FontColor(Colors.Blue.Medium)
                    .AlignCenter();

                page.Content().Column(col =>
                {
                    col.Spacing(12);

                    col.Item().Text("Passenger Information").Bold().FontSize(16);
                    col.Item().Text($"Name: {passenger.FirstName} {passenger.LastName}");
                    col.Item().Text($"Passport: {passenger.PassportNumber}");
                    col.Item().Text($"Phone: {passenger.PhoneNumber}");
                    col.Item().Text($"Email: {passenger.Email}");

                    col.Item().PaddingVertical(10).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                    col.Item().Text("Flight Details").Bold().FontSize(16);
                    col.Item().Text($"Flight Number: {flight.FlightNumber}");
                    col.Item().Text($"Airplane Type: {flight.AirplaneType}");
                    col.Item().Text($"From: {flight.Departure} → To: {flight.Arrival}");
                    col.Item().Text($"Departure: {flight.DepartureTime:yyyy-MM-dd HH:mm}");
                    col.Item().Text($"Arrival: {flight.ArrivalTime:yyyy-MM-dd HH:mm}");
                });

                page.Footer()
                    .AlignCenter()
                    .Text($"Generated by FlightsReservation — {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC")
                    .FontSize(10).FontColor(Colors.Grey.Medium);
            });
        });

        document.GeneratePdf(stream);
        stream.Position = 0;

        await Task.CompletedTask;
        return stream;
    }
}